# from https://einvoice1.gst.gov.in/Documents/EINVOICE_SCHEMA.xlsx,

STATES = {
    "1": "JAMMU_AND_KASMIR",
    "2": "HIMACHAL_PRADESH",
    "3": "PUNJAB",
    "4": "CHANDIGARH",
    "5": "UTTARAKHAND",
    "6": "HARYANA",
    "7": "DELHI",
    "8": "RAJASTHAN",
    "9": "UTTAR_PRADESH",
    "10": "BIHAR",
    "11": "SIKKIM",
    "12": "ARUNACHAL_PRADESH",
    "13": "NAGALAND",
    "14": "MANIPUR",
    "15": "MIZORAM",
    "16": "TRIPURA",
    "17": "MEGHALAYA",
    "18": "ASSAM",
    "19": "WEST_BENGAL",
    "20": "JHARKHAND",
    "21": "ORISSA",
    "22": "CHHATTISGARH",
    "23": "MADHYA_PRADESH",
    "24": "GUJARAT",
    "25": "DAMAN_AND_DIU",
    "26": "DADAR_AND_NAGAR_HAVELI",
    "27": "MAHARASTRA",
    "29": "KARNATAKA",
    "30": "GOA",
    "31": "LAKSHADWEEP",
    "32": "KERALA",
    "33": "TAMIL_NADU",
    "34": "PONDICHERRY",
    "35": "ANDAMAN_AND_NICOBAR",
    "36": "TELENGANA",
    "37": "ANDHRA_PRADESH",
    "38": "LADAKH",
    "97": "OTHER_TERRITORY",
    "96": "OTHER_COUNTRIES",
}
