name: Automated Testing

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Checking python version
        run: python --version

      - name: Install dependencies from requirements
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install .

      - name: Check imports
        run: |
          python -c "from gst_irn import Session"
